# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_DwEJ0Yrstv3ha5HezoYghlRjcO5gBwg
"""

a=int(input())
if a==1:
  print('январь')
elif a==2:
  print('февраль')
elif a==3:
  print('март')
elif a==4:
  print('апрель')
elif a==5:
  print('май')
elif a==6:
  print('июнь')
elif a==7:
  print('июль')
elif a==8:
  print('август')
elif a==9:
  print('сентябрь')
elif a==10:
  print('октябрь')
elif a==11:
  print('ноябрь')
elif a==12:
  print('декабрь')
else:
  print('error')

a=int(input())
if a%2==0:
  print('четное')
else:
  print('нечетное')

n=int(input())
if n>40:
  print('stonks')
if n<40:
  print('not stonks')

def is_year_leap():
  year=int(input())
  if year%4!=0 or (year%100==0 and year%400!=0):
    print('false')
  else:
    print('true')
is_year_leap()

def is_prime():
  n=int(input())
  k=0
  for i in range(2, n//2+1):
    if n%i==0:
      k+=1
  if k<=0:
    print('true')
  else:
    print('false')
is_prime()

a=float(input())
b=float(input())
if a/b==3.6 or (b >=((-138/2)**1.3) and b<=((-69)/(28**5.1)*4)):
  temp=a
  a=b
  b=temp
  print(a)
  print(b)
else:
  print(a,b)

a=int(input())
b=int(input())
c=int(input())
d=int(input())
s=int(input())
k=0
z=0
m=0
if a!=b and a!=c and a!=d and a!=s and b!=c and b!=d and b!=s and c!=d and c!=s and d!=s:
  print('уникальные')
if a%2==0:
  k+=1
if b%2==0:
  k+=1
if c%2==0:
  k+=1
if d%2==0:
  k+=1
if s%2==0:
  k+=1
if a<0:
  z+=1
if b<0:
  z+=1
if c<0:
  z+=1
if d<0:
  z+=1
if s<0:
  z+=1
if a>=-256 and a<=1024:
  m+=1
if b>=-256 and b<=1024:
  m+=1
if c>=-256 and c<=1024:
  m+=1
if d>=-256 and d<=1024:
  m+=1
if s>=-256 and s<=1024:
  m+=1
print(k,z,m)

