# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GnWO61cdzJRXWu6PDcje-KbUaSSK02YU
"""

a=5
b=int(input())
x=a*b
print(x)

a=int(input())
b=int(input())
x=(a+b)**2
print(x)

a=15
b=10
c=int(input())
x=(a+b)/c
print(x)

a=int(input())
b=int(input())
x=a**2+2*a*b+b**2
print(x)

a=int(input())
b=int(input())
c=int(input())
p=a+b+c
p1=(a+b+c)/2
s=(p1*(p1-a)*(p1-b)*(p1-c))**0.5
print(p,s)

a=int(input())
b=int(input())
x= (((a**3+14))/5)*b
print(x)

a=int(input())
n=int(input())
x=(a**2)//n
print(x)

a=float(input())
b=float(input())
c=int(input())
d=int(input())
x=int(input())
z=int(input())
e=a//b
y=c*d
t=x%z
print(e,y,t)

n=int(input())
d=n//86400
g=n//3600
s=n//60
print(d,g,s)

n=str(input())
print(n,n*2,n*3)